# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a92df5361192b9d506f255d69019d0160be0f88f02a0989e9c7e2927f73b3b023e978303268753087603e4699ec02f1d99bd3edc1b52e4973eed82a491b6e02f

test:
  secret_key_base: a07e022f09beefad96bad62e7a2982d2e5a017132092c9d4cc8fb9c6d6e63e9f82d0f3bf7f5b2b9e3287d4f4e25bbd5999c2be18bce41afbdaa8c9e7f9c90906

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
